"""baseline

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('target', sa.String(length=1024), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('consent_live', sa.Boolean(), nullable=False),
    sa.Column('consent_recordings', sa.Boolean(), nullable=False),
    sa.Column('consent_training', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_problems',
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('s3_key')
    )
    op.create_table('raw_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key', 'etag')
    )
    op.create_table('s3_cursors',
    sa.Column('prefix', sa.String(length=512), nullable=False),
    sa.Column('last_full_scan', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('prefix')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=False),
    sa.Column('tailscale_host', sa.String(length=255), nullable=False),
    sa.Column('ssh_user', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id'),
    sa.UniqueConstraint('site')
    )
    op.create_index(op.f('ix_devices_customer_id'), 'devices', ['customer_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('s3_prefix', sa.String(length=1024), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_family'), 'refresh_tokens', ['family'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_staff_id'), 'refresh_tokens', ['staff_id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_pk', 'name')
    )
    op.create_index(op.f('ix_cameras_device_pk'), 'cameras', ['device_pk'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_pk', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=False),
    sa.Column('camera', sa.String(length=128), nullable=False),
    sa.Column('stem', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('start_ts', sa.Float(), nullable=False),
    sa.Column('end_ts', sa.Float(), nullable=True),
    sa.Column('trigger_ts', sa.BigInteger(), nullable=True),
    sa.Column('day', sa.String(length=10), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('alert_command', sa.String(length=32), nullable=True),
    sa.Column('alert_reason', sa.Text(), nullable=False),
    sa.Column('detected', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('class_max_conf', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('owner_verdicts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('dispatch', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('completeness', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('clip_start_local', sa.String(length=64), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('frame_size', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(summary,''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_pk', 'camera', 'stem')
    )
    op.create_index('ix_events_camera_start', 'events', ['camera', 'start_ts'], unique=False)
    op.create_index('ix_events_completeness', 'events', ['completeness'], unique=False, postgresql_using='gin')
    op.create_index('ix_events_device_start', 'events', ['device_pk', 'start_ts'], unique=False)
    op.create_index('ix_events_search', 'events', ['search'], unique=False, postgresql_using='gin')
    op.create_table('owner_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_pk', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('cameras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('first_ts', sa.Float(), nullable=True),
    sa.Column('last_ts', sa.Float(), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_notices_device_pk'), 'owner_notices', ['device_pk'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('camera', sa.String(length=128), nullable=True),
    sa.Column('stem', sa.String(length=255), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_artifacts_event_id'), 'artifacts', ['event_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'event_id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_pk', sa.Integer(), nullable=False),
    sa.Column('alert_stem', sa.String(length=255), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('scope_camera', sa.String(length=128), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_feedback_device_pk'), 'feedback', ['device_pk'], unique=False)
    op.create_index(op.f('ix_feedback_event_id'), 'feedback', ['event_id'], unique=False)
    op.create_table('review_state',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('by', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['by'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('parsed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_artifact_id', sa.Integer(), nullable=True),
    sa.Column('input_artifact_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_event_id'), 'ai_runs', ['event_id'], unique=False)
    op.execute("""
    CREATE FUNCTION audit_log_reject() RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'audit_log is append-only';
    END;
    $$ LANGUAGE plpgsql
    """)
    op.execute("""
    CREATE TRIGGER audit_log_no_update BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_reject()
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_update ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_reject()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_runs_event_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_table('review_state')
    op.drop_index(op.f('ix_feedback_event_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_device_pk'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_artifacts_event_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_owner_notices_device_pk'), table_name='owner_notices')
    op.drop_table('owner_notices')
    op.drop_index('ix_events_search', table_name='events', postgresql_using='gin')
    op.drop_index('ix_events_device_start', table_name='events')
    op.drop_index('ix_events_completeness', table_name='events', postgresql_using='gin')
    op.drop_index('ix_events_camera_start', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_cameras_device_pk'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_refresh_tokens_staff_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('exports')
    op.drop_index(op.f('ix_devices_customer_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('collections')
    op.drop_table('staff')
    op.drop_table('s3_cursors')
    op.drop_table('raw_revisions')
    op.drop_table('index_problems')
    op.drop_table('customers')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
