"""Copy for the scene map editor, in Hebrew and English; keys stay stable, like strings.TEXT.

The editor speaks the app's language (``strings.LANG``, what setup and every other screen show), Hebrew right to
left. ``--lang`` previews the other language of this editor only. Read with ``st(key, lang, **values)``.
"""

LANGS = ("he", "en")

TEXT = {
    "en": dict(
        map_button="Map",
        map_button_tip="Mark whose ground each part of this camera's picture is",
        window_title="{camera} · Map",
        eyebrow="Camera map",
        setup_eyebrow="Camera {number} of {total}",
        camera_fallback="Camera {number} of {total}",
        camera_plain="Camera",

        tab_regions="Numbered places",
        tab_draw="Draw by hand",
        tab_lines="Boundaries",
        tab_saved="Saved map",

        saved_on="Saved {when}",
        kept_hint="This is the map the box keeps for this camera. Tap a place to rename it, change whose it is or "
                  "delete it. Draw more by hand, or start over.",
        kept_title="Area {number}",
        kept_empty="No saved places left. Draw by hand, or start over.",
        merged_note="{count} duplicate places were merged into one each. Saving cleans them on the box too.",
        merged_note_one="1 duplicate place was merged. Saving cleans it on the box too.",
        moved_note="This map was carried over from the camera’s previous name. Save to keep it under the new one.",
        start_over="Start over",
        start_over_question="Delete the map of {camera} and start over? The saved map stays until you save.",
        start_over_yes="Yes, start over",
        start_over_no="Keep the map",

        regions_hint="Tap a number on the picture or in the list, then choose whose it is.",
        grid_note="Automatic outlining was not available, so the picture was split into squares. "
                  "Answer for the squares you know.",
        regions_empty="The box found no places to number in this picture. Draw the areas by hand instead.",
        region_title="Place {number}",
        choice_mine="Ours",
        choice_neighbour="Neighbour’s",
        choice_public="Street",
        choice_hide="Hide",
        hint_mine="Alerts as today",
        hint_neighbour="Seen, no routine alerts",
        hint_public="Passers-by are normal",
        hint_hide="Blacked out for privacy",
        choice_boundary="It is the boundary (railing, wall, fence)",
        hint_boundary="Ours, and crossing it towards us counts",
        tag_boundary="Boundary",
        side_question="Which side of {name} is ours?",
        side_hint="Nothing around it says which side is ours. Tap our side; the arrow on the picture shows it.",
        boundary_name="the boundary {number}",
        walls_unclear="Say which side is ours for: {names}. Until then it is saved without its line.",
        restore_button="Restore the previous map",
        restore_from="from {when}",
        restore_none="There is no previous map yet: one is kept each time a map is saved.",
        restoring="Restoring…",
        restored_title="The previous map is back",
        restored_receipt="I restored the previous map of {camera}. It is working now.",
        choice_skip="Skip",
        choice_unknown="Don’t know",
        tag_none="Not answered",
        tag_skip="Skipped",
        tag_unknown="Don’t know",
        name_placeholder="Name (optional), e.g. the lawn",
        answered="{count} of {total} answered",

        draw_hint="Click the corners on the picture. Double-click, or click the first corner, to close the shape. "
                  "Drag a corner to move it.",
        draw_new="New area",
        draw_corners="{count} corners · double-click to finish",
        draw_first="Click the first corner on the picture",
        draw_undo="Undo corner",
        draw_stop="Stop drawing",
        draw_empty="No areas drawn yet.",
        hand_title="Drawn area {number}",
        watched_name="Watched area (until now)",
        delete="Delete",
        choose_kind="Choose whose it is",

        line_hint="A boundary is a line people cross onto our ground: the railing, the gate. "
                  "Click two points along it, then click on our side.",
        line_new="New boundary",
        line_step_a="Click where the boundary starts",
        line_step_b="Click where it ends",
        line_step_side="Click on our side of the line",
        line_from_areas="Our side from the areas",
        line_from_areas_tip="Takes our side from the areas marked as ours next to the line",
        line_no_areas="No area of ours is next to the middle of the line. Click on our side instead.",
        line_on_line="That point is on the line itself. Click a little to one side.",
        line_cancel="Cancel",
        line_title="Boundary {number}",
        line_name_placeholder="Name (optional), e.g. the railing",
        line_flip="The other side is ours",
        line_empty="No boundaries yet.",

        count_mine="{count} ours",
        count_neighbour="{count} neighbour’s",
        count_public="{count} street",
        count_hide="{count} hidden",
        count_lines="{count} boundaries",
        count_line_one="1 boundary",
        nothing_marked="Nothing marked yet",
        save="Save map",
        save_next="Save & next",
        cancel="Cancel",

        summary_title="Save this map?",
        summary_hint="This is what the box will keep for this camera.",
        tile_mine="Ours",
        tile_neighbour="Neighbour’s",
        tile_public="Street",
        tile_hide="Hidden",
        tile_lines="Boundaries",
        rest_unmapped="The rest of the picture is watched as today.",
        rest_neighbour="The rest of the picture is the neighbour’s: seen, no routine alerts.",
        rest_public="The rest of the picture is the street: seen, no routine alerts.",
        rest_hide="Outside the watched area is hidden, as before.",
        left_out="Areas without an answer are not saved ({count}).",
        restart_note="The cameras restart for a moment so the hidden parts apply.",
        summary_save="Save",
        summary_back="Back to editing",
        saving="Saving on the box…",

        saved_title="Map saved",
        saved_hint="This is the map the box keeps for this camera.",
        saved_restart="The cameras are restarting for a moment.",
        done="Done",
        next_camera="Next camera",
        finish="Finish",
        toast_saved="Map saved",

        loading_title="Looking at the picture",
        loading_hint="The box is outlining what it sees. This can take a few seconds.",
        legend_title="What each colour means",
        legend_mine="Ours: a person here alerts, as today.",
        legend_neighbour="The neighbour’s: seen; alerts only on something suspicious, or when someone crosses onto ours.",
        legend_public="Street: passers-by are normal; alerts only on something suspicious.",
        legend_hide="Hidden: blacked out. Never seen, recorded or sent.",

        error_title="That did not work",
        error_unreachable="The box could not be reached. Check that it is on and connected, then try again.",
        error_no_answer="The box did not answer. Try again.",
        error_box_refused="The box could not do that.",
        error_bad_answer="The box’s answer could not be read. Try again.",
        error_bad_picture="The picture from the box could not be read. Try again.",
        error_too_detailed="The map has too many corners to send. Delete a few corners or areas, then save again.",
        error_invalid="The map could not be saved: {detail}",
        error_detail="The box said: {detail}",
        try_again="Try again",

        setup_title="The map of each camera",
        setup_hint="Mark whose ground each part of the picture is. You can skip this and do it later from the "
                   "Cameras page.",
        setup_back="Back",
        setup_skip="Skip for now",
        setup_skip_all="Finish without maps",
        state_saved="Saved",
        state_skipped="Skipped",
    ),
    "he": dict(
        map_button="המפה",
        map_button_tip="סמנו של מי כל חלק בתמונה של המצלמה",
        window_title="{camera} · המפה",
        eyebrow="המפה של המצלמה",
        setup_eyebrow="מצלמה {number} מתוך {total}",
        camera_fallback="מצלמה {number} מתוך {total}",
        camera_plain="מצלמה",

        tab_regions="מקומות ממוספרים",
        tab_draw="ציור ידני",
        tab_lines="קווי גבול",
        tab_saved="המפה השמורה",

        saved_on="נשמרה ב-{when}",
        kept_hint="זו המפה שהקופסה שומרת למצלמה הזאת. לחצו על מקום כדי לשנות את השם שלו, של מי הוא, או למחוק "
                  "אותו. אפשר לצייר עוד ביד, או להתחיל מחדש.",
        kept_title="אזור {number}",
        kept_empty="לא נשארו מקומות שמורים. אפשר לצייר ביד, או להתחיל מחדש.",
        merged_note="אוחדו {count} מקומות כפולים. השמירה תנקה אותם גם בקופסה.",
        merged_note_one="אוחד מקום כפול אחד. השמירה תנקה אותו גם בקופסה.",
        moved_note="המפה הועברה מהשם הקודם של המצלמה. שמרו כדי לקבע אותה בשם החדש.",
        start_over="להתחיל מחדש",
        start_over_question="למחוק את המפה של {camera} ולהתחיל מחדש? המפה השמורה תישאר עד שתשמרו.",
        start_over_yes="כן, להתחיל מחדש",
        start_over_no="להשאיר את המפה",

        regions_hint="לחצו על מספר בתמונה או ברשימה, ובחרו של מי המקום.",
        grid_note="הסימון האוטומטי לא היה זמין, ולכן התמונה חולקה לריבועים. ענו על הריבועים שאתם מכירים.",
        regions_empty="הקופסה לא מצאה מקומות למספר בתמונה הזאת. אפשר לצייר את האזורים ביד.",
        region_title="מקום {number}",
        choice_mine="שלנו",
        choice_neighbour="של השכן",
        choice_public="רחוב",
        choice_hide="להסתיר",
        hint_mine="התראות כרגיל",
        hint_neighbour="נצפה, בלי התראות שגרה",
        hint_public="עוברים ושבים זה רגיל",
        hint_hide="מושחר לפרטיות",
        choice_boundary="זה הגבול (מעקה, קיר, גדר)",
        hint_boundary="שלנו, ומעבר דרכו אלינו נספר",
        tag_boundary="גבול",
        side_question="איזה צד של {name} שלנו?",
        side_hint="שום דבר סביבו לא אומר איזה צד שלנו. בחרו את הצד שלנו; החץ בתמונה מראה אותו.",
        boundary_name="הגבול {number}",
        walls_unclear="חסר הצד שלנו עבור: {names}. עד אז הוא יישמר בלי הקו שלו.",
        restore_button="שחזר מפה קודמת",
        restore_from="מ-{when}",
        restore_none="עוד אין מפה קודמת: אחת נשמרת בכל פעם שמפה נשמרת.",
        restoring="משחזרים…",
        restored_title="המפה הקודמת חזרה",
        restored_receipt="החזרתי את המפה הקודמת של {camera}. היא פועלת עכשיו.",
        choice_skip="דלג",
        choice_unknown="לא יודע",
        tag_none="עוד לא נענה",
        tag_skip="דילגתם",
        tag_unknown="לא ידוע",
        name_placeholder="שם (לא חובה), למשל הדשא",
        answered="{count} מתוך {total} נענו",

        draw_hint="לחצו על הפינות בתמונה. לחיצה כפולה, או לחיצה על הפינה הראשונה, סוגרת את הצורה. "
                  "גררו פינה כדי להזיז אותה.",
        draw_new="אזור חדש",
        draw_corners="{count} פינות · לחיצה כפולה לסיום",
        draw_first="לחצו על הפינה הראשונה בתמונה",
        draw_undo="ביטול פינה",
        draw_stop="הפסקת הציור",
        draw_empty="עוד לא צוירו אזורים.",
        hand_title="אזור מצויר {number}",
        watched_name="האזור שנצפה עד היום",
        delete="מחיקה",
        choose_kind="בחרו של מי זה",

        line_hint="קו גבול הוא קו שעוברים בו אל השטח שלנו: המעקה, השער. לחצו על שתי נקודות לאורכו, ואז לחצו "
                  "בצד שלנו.",
        line_new="קו גבול חדש",
        line_step_a="לחצו איפה שהגבול מתחיל",
        line_step_b="לחצו איפה שהוא נגמר",
        line_step_side="לחצו בצד שלנו של הקו",
        line_from_areas="הצד שלנו לפי האזורים",
        line_from_areas_tip="לוקח את הצד שלנו מהאזורים שסומנו כשלנו ליד הקו",
        line_no_areas="אין אזור שלנו ליד אמצע הקו. לחצו בצד שלנו.",
        line_on_line="הנקודה הזאת על הקו עצמו. לחצו קצת הצידה.",
        line_cancel="ביטול",
        line_title="קו גבול {number}",
        line_name_placeholder="שם (לא חובה), למשל המעקה",
        line_flip="הצד השני שלנו",
        line_empty="עוד אין קווי גבול.",

        count_mine="{count} שלנו",
        count_neighbour="{count} של השכן",
        count_public="{count} ברחוב",
        count_hide="{count} מוסתרים",
        count_lines="{count} קווי גבול",
        count_line_one="קו גבול אחד",
        nothing_marked="עוד לא סומן כלום",
        save="שמירת המפה",
        save_next="שמירה והמשך",
        cancel="ביטול",

        summary_title="לשמור את המפה?",
        summary_hint="זה מה שהקופסה תשמור למצלמה הזאת.",
        tile_mine="שלנו",
        tile_neighbour="של השכן",
        tile_public="רחוב",
        tile_hide="מוסתרים",
        tile_lines="קווי גבול",
        rest_unmapped="שאר התמונה נצפה כמו היום.",
        rest_neighbour="שאר התמונה של השכן: נצפה, בלי התראות שגרה.",
        rest_public="שאר התמונה הוא רחוב: נצפה, בלי התראות שגרה.",
        rest_hide="מחוץ לאזור הנצפה מוסתר, כמו קודם.",
        left_out="אזורים בלי תשובה לא יישמרו ({count}).",
        restart_note="המצלמות יופעלו מחדש לרגע כדי שההסתרה תחול.",
        summary_save="שמירה",
        summary_back="חזרה לעריכה",
        saving="שומרים בקופסה…",

        saved_title="המפה נשמרה",
        saved_hint="זו המפה שהקופסה שומרת למצלמה הזאת.",
        saved_restart="המצלמות מופעלות מחדש לרגע.",
        done="סיום",
        next_camera="למצלמה הבאה",
        finish="סיום",
        toast_saved="המפה נשמרה",

        loading_title="מסתכלים על התמונה",
        loading_hint="הקופסה מסמנת את מה שהיא רואה. זה יכול לקחת כמה שניות.",
        legend_title="מה אומר כל צבע",
        legend_mine="שלנו: אדם כאן מתריע, כמו היום.",
        legend_neighbour="של השכן: נצפה, ומתריע רק על משהו חשוד או כשמישהו עובר אלינו.",
        legend_public="רחוב: עוברים ושבים זה רגיל; מתריע רק על משהו חשוד.",
        legend_hide="מוסתר: מושחר. לא נצפה, לא מוקלט ולא נשלח.",

        error_title="זה לא הצליח",
        error_unreachable="אין חיבור לקופסה. בדקו שהיא דולקת ומחוברת, ונסו שוב.",
        error_no_answer="הקופסה לא ענתה. נסו שוב.",
        error_box_refused="הקופסה לא הצליחה לעשות את זה.",
        error_bad_answer="לא הצלחנו לקרוא את התשובה של הקופסה. נסו שוב.",
        error_bad_picture="לא הצלחנו לקרוא את התמונה מהקופסה. נסו שוב.",
        error_too_detailed="במפה יש יותר מדי פינות לשליחה. מחקו כמה פינות או אזורים, ושמרו שוב.",
        error_invalid="לא הצלחנו לשמור את המפה: {detail}",
        error_detail="הקופסה אמרה: {detail}",
        try_again="נסו שוב",

        setup_title="המפה של כל מצלמה",
        setup_hint="סמנו של מי כל חלק בתמונה. אפשר לדלג ולעשות את זה אחר כך מעמוד המצלמות.",
        setup_back="חזרה",
        setup_skip="דלג לעכשיו",
        setup_skip_all="לסיים בלי מפות",
        state_saved="נשמר",
        state_skipped="דילגתם",
    ),
}

assert set(TEXT["en"]) == set(TEXT["he"]), "every key in both languages"

_preview = None


def set_language(lang):
    """Preview the editor in *lang* for this run (``--lang``); None follows the app's language again."""
    global _preview
    _preview = lang if lang in LANGS else None


def language():
    """The app's language (strings.LANG), unless a preview asked for the other one."""
    from .strings import LANG
    return _preview or (LANG if LANG in LANGS else "en")


def st(key, lang=None, **values):
    from .strings import isolate
    lang = lang if lang in LANGS else language()
    return TEXT[lang][key].format(**{k: isolate(v, lang) for k, v in values.items()})
