"""All visible application copy; keys remain stable for translation."""

TEXT = {
    "chat_image_unavailable": "Picture unavailable",
    "premium_security": "Security & notifications",
    "premium_viewing": "Camera viewing",
    "premium_view_hint": "Hide the camera pictures on this screen while Home Guard keeps watching your home.",

    "premium_live": "LIVE",
    "premium_home": "HOME GUARD / {house}",
    "premium_protecting": "Protecting the house",
    "premium_collecting": "Recording the house",
    "ai_assistant": "AI assistant",
    "ai_thinking": "AI is looking at {camera}\u2026",
    "ai_watching": "Watching {count} cameras",
    "ai_quiet_line": "AI checked {camera}: {text} - no alert",
    "chat_button": "{name}: {text}",
    "chat_meta": "{name}   {time}",
    "chat_delivered": "Sent to the family",
    "chat_refused": "NOT DELIVERED",
    "demo_chat_alert": "A person is waiting at the front door. They appear to be carrying a delivery.",
    "demo_chat_owner": "That's our delivery. Is anyone else outside?",
    "demo_chat_answer": "I only see the delivery driver at the door. The driveway is clear.",
    "demo_chat_hebrew": "\u05d0\u05e0\u05d9 \u05d1\u05d1\u05d9\u05ea, \u05d0\u05e4\u05ea\u05d7 \u05dc\u05d5 \u05d0\u05ea \u05d4\u05d3\u05dc\u05ea.",
    "demo_chat_button": "False alarm",
    "demo_chat_maya": "Please keep watching the garden while we have dinner.",
    "demo_chat_answer2": "Of course. I'll keep watching the garden and let you know if someone approaches.",

    "ai_delivery_banner": "Alerts are NOT reaching Telegram",
    "ai_activity": "AI activity",
    "ai_sent": "Alert sent",
    "ai_urgent_sent": "Urgent alert sent",
    "ai_training": "No alert - nothing happening (saved for training)",
    "ai_muted": "Not sent - alerts are paused",
    "ai_not_sent": "NOT SENT",
    "ai_empty": "No activity yet. When a camera sees a person or a vehicle, the AI's answer appears here.",
    "ai_stopped": "Home Guard is stopped",
    "ai_not_updating": "The AI status is not updating",
    "ai_record_meta": "{time} | {camera} | {labels}",
    "ai_no_summary": "No description was recorded.",
    "ai_no_error": "No delivery reason was recorded. Check the Telegram connection.",
    "demo_ai_person": "A person is walking along the driveway toward the front door.",
    "demo_ai_cars": "Several cars are parked in the driveway. Nothing is moving.",
    "demo_ai_paused": "A person is standing beside the garden gate.",
    "demo_ai_urgent": "Two people are trying to force the front door open.",
    "demo_ai_refused": "The bot is not a member of the group chat. Add the bot to the Telegram group again.",

    "detection_label": "{label} \u00b7 {percent}%",
    "detector_sees": "Sees: {objects}",
    "object_count": "{count} {label}",
    "object_person": "person", "object_person_plural": "people",
    "object_car": "car", "object_car_plural": "cars",
    "object_truck": "truck", "object_truck_plural": "trucks",
    "object_bus": "bus", "object_bus_plural": "buses",
    "object_bicycle": "bicycle", "object_bicycle_plural": "bicycles",
    "object_motorcycle": "motorcycle", "object_motorcycle_plural": "motorcycles",
    "detector_nothing": "Nothing right now",
    "detector_not_looking": "Detector is not looking at this camera",

    "camera_search_wait": "Looking for cameras. Some devices may take a few minutes to answer.",
    "camera_search_elapsed": "Searching - {minutes}m {seconds}s",

    "camera_changes_save_failed": "The camera changes could not be saved. Check the camera names and try again.",
    "camera_setup_finished": "Setup finished - {house}\n{count} cameras found: {names}",
    "camera_none_found": "None found",
    "camera_check_only_hint": "Camera check only. Setup will not be run.",
    "camera_photos_load_failed": "The camera photos could not be loaded",
    "camera_save_failed": "The camera changes could not be saved. Your setup is still complete.",
    "skip_camera_check": "Skip the camera check",
    "only_check_cameras": "Only check this box's cameras",

    "detail_camera_refused_count": "{count} of {total} cameras refused the login.",
    "detail_recorder_answers": "{count} cameras answer on the recorder.",
    "detail_channel_ok": "Camera {channel} sent a picture ({size}).",
    "detail_channel_no_picture": "Camera {channel} answers, but no picture arrived.",
    "detail_device_skipped": "A device did not answer and was skipped.",
    "detail_camera_found": "Camera found: {name} ({size}).",

    "demo_box_name": "Home Guard box",
    "box_label": "The box",
    "box_loading": "Looking for Windows boxes on this laptop's Tailscale network...",
    "box_address_placeholder": "Box address, for example 100.100.100.10",
    "box_user_label": "Windows user name on the box",
    "box_user_help": "The Windows account on the box. On the box, open Command Prompt and type whoami; it is the part after the backslash.",
    "box_manual": "Type an address",
    "box_peer": "{name} - {address}",
    "box_offline": " (offline)",
    "box_pick_hint": "Choose the customer's box by name, or type its address.",
    "box_address_help": "On this laptop, open Tailscale and copy the address of the customer's box.",
    "box_target_error": "Enter the box address and its Windows user name (letters, digits, underscores, dots or hyphens).",

    "camera_login_help": "The user name is usually admin. Use the password set when the cameras were installed, the recorder's admin password, or the code on the camera label.",
    "camera_lock_warning": "Before trying a third time: some cameras lock logins for a while after repeated failures. Check the password before continuing.",
    "retry_confirming": "Confirming the earlier steps, then trying the new camera login.",
    "technical_log": "Technical log",
    "copy_log": "Copy",
    "details_empty": "No additional notes for this step yet.",
    "detail_login_refused": "A camera refused this login. Check its user name and password.",
    "detail_timeout": "A camera did not send a picture in time. Check its power and connection.",
    "detail_no_stream": "No working picture address was found for a camera.",
    "detail_try_stream": "Trying another picture address for a camera.",
    "detail_find_cameras": "Looking for cameras on the home network.",
    "detail_update": "Updating the software on the box.",
    "detail_copy": "Copying setup files to the box.",
    "detail_command": "Running a setup command on the box.",

    "camera_check_pending": "Finish loading the camera check before continuing. If it failed, refresh the photos and try again.",

    "setup_window_title": "Home Guard Setup",
    "address_not_remembered": "The box address could not be remembered. Enter it again next time.",

    "check_cameras_title": "Check the cameras",
    "check_cameras_hint": "Confirm the views, names and enabled cameras, or skip this check and finish.",
    "camera_snapshot_failed": "Could not take a photo. Check camera power and connection, then refresh.",
    "remote_cameras_saved": "Camera changes saved on the box.",
    "camera_check_continue": "Finish setup",
    "camera_check_unsaved": "Save your camera changes before finishing setup.",

    "setup_live_hint": "Set up the box for this home. Changes begin only after you review and start setup.",
    "review_title": "Review your setup",
    "review_hint": "Check these choices before making changes to the box.",
    "review_text": "You are about to set up box {target}\n\nNetwork: {network}\nHouse: {house}\nSecurity alerts: {alerts}\nCameras: {cameras}",
    "alerts_on_review": "On - {hours}; {minutes:g} minutes between alerts",
    "alerts_off_review": "Off - save clips only",
    "cameras_find_review": "Find and check the cameras",
    "cameras_later_review": "Set up cameras later",
    "start_setup": "Start setup",
    "powershell_missing": "Windows PowerShell is missing. Install it, then try again.",
    "engine_missing": "The setup program is missing. Restore the Home Guard setup folder, then try again.",
    "engine_launch_error": "The setup program could not run. Check that it is installed, then try again.",
    "engine_incomplete": "Setup ended before every step finished. Check the box connection and try again.",
    "engine_protocol_error": "The setup program reported steps out of order. Update the setup program and try again.",
    "setup_step_complete": "Finished",
    "setup_elapsed": "Working - {seconds}s",
    "cancel_setup": "Cancel setup",
    "setup_cancelled": "Setup cancelled. Changes already made on the box may remain.",
    "live_summary_hint": "Setup finished. Complete the checks below before leaving.",
    "step_connect": "Connect to the box",
    "step_update": "Update software",
    "step_site": "Save home preferences",
    "step_network": "Connect the home network",
    "step_cameras": "Find cameras",
    "step_alerts": "Set security alerts",
    "step_readiness": "Check readiness",
    "step_skip": "Skipped",

    "address_error": "Enter a box address like installer@box.example.",
    "ssid_error": "Enter the home Wi-Fi network name.",
    "wifi_password_error": "Enter a network password with 8 to 63 characters.",
    "house_error": "Use lowercase letters, numbers and underscores, like cedar_house.",
    "camera_user_error": "Enter the login name used by the cameras.",
    "camera_password_error": "Enter the password used by the cameras.",
    "step_names": ["Connect", "Network", "Home", "Cameras", "Ready"],
    "step_number": "{number}. {name}",
    "step_done": "\u2713 {name}",
    "event_line": "{time}  {text}",
    "time_unavailable": "Time unavailable",

    "summary_house": "Home: {house}",
    "enlarge_hint": "Choose a camera below. Double-click the main picture for full screen.",

    "stopped_banner": "Home Guard is stopped. Your home is not being watched.",
    "close_stopped": "Home Guard is stopped. Start it to watch your home again.",
    "close_starting": "Home Guard is starting. Watching has not resumed yet.",
    "all_day_choice": "All day",
    "hours_from": "From",
    "hours_to": "To",
    "watching": "Watching",
    "paused_until": "Alerts paused until {time}",
    "paused_some": "Some camera alerts paused until {time}",
    "resume_alerts": "Resume alerts",

    "cameras_title": "Your cameras",
    "cameras_hint": "Choose which cameras protect your home. Use lowercase letters, numbers and underscores for names. Refreshing photos may take a few moments per camera.",
    "refresh_photos": "Refresh photos",
    "save_cameras": "Save cameras",
    "camera_working": "Working on your cameras...",
    "camera_ready": "Photos loaded. Make your changes, then save.",
    "camera_saved": "Camera changes saved. The box is applying them.",
    "camera_error": "We could not finish. Check your cameras and try again.",
    "camera_empty": "No cameras are configured for this box yet.",
    "camera_no_photo": "No picture available",
    "camera_enabled": "Enabled",
    "camera_name": "Camera name",
    "camera_names_invalid": "Give every camera a different name using lowercase letters, numbers and underscores.",
    "cameras_page": "Cameras",

    "overview": "Overview",
    "settings": "Settings",
    "settings_title": "How Home Guard protects your home",
    "settings_hint": "Changes apply to this box. Your cameras keep their existing login details.",
    "security_alerts": "Security alerts",
    "security_alerts_hint": "On: watch the home and send alerts. Off: only save camera clips.",
    "alert_from": "Alerts from (hour)",
    "alert_until": "Alerts until (hour)",
    "all_day": "Alerts can arrive all day.",
    "hours_window": "Alerts from {start:02d}:00 until {end:02d}:00.",
    "hours_overnight": "Alerts from {start:02d}:00 tonight until {end:02d}:00 tomorrow.",
    "cooldown": "Minutes between alerts from the same camera",
    "minutes_suffix": " minutes",
    "cooldown_hint": "From 10 seconds to 24 hours. Times are saved to the nearest second.",
    "save_settings": "Save settings",
    "settings_saved": "Saved.",
    "saved_stopped": "Saved. Choose Start Home Guard to use these settings.",
    "applying": "Applying settings - Home Guard is restarting...",
    "restarting": "Restarting",
    "applying_hint": "Your new settings are saved. Waiting for Home Guard to start again.",
    "apply_slow": "Still waiting for Home Guard. Check that the box is running.",
    "applied": "Settings applied. Home Guard is running.",
    "stop_box": "Stop Home Guard",
    "start_box": "Start Home Guard",
    "stop_confirm": "Stop protecting this home?",
    "stop_explanation": "Camera recording and security alerts will stop. Home Guard stays stopped, even after a restart, until you choose Start Home Guard.",
    "keep_running": "Keep running",
    "stopped_title": "Home Guard is stopped",
    "stopped_hint": "Recording and alerts are off. Choose Start Home Guard to protect this home again.",
    "start_pending": "Starting Home Guard...",
    "control_error": "The change could not be saved. Please try again.",
    "step_error": "This step could not finish. Check the box and try again.",
    "date_format": "%d %b, %H:%M",
    "brand": "HOME GUARD",
    "home": "Your home, in view.",
    "demo": "DEMONSTRATION",
    "collecting": "Collecting",
    "stopped": "Stopped",
    "collection": "Saving clips",
    "inference": "Security alerts",
    "upload": "Last upload",
    "waiting": "Clips waiting",
    "disk": "Disk free",
    "never": "No upload yet",
    "cameras": "Cameras",
    "live": "LIVE",
    "offline": "No picture",
    "offline_hint": "Waiting for a fresh picture",
    "pictures_off": "Camera pictures are switched off",
    "pictures_hint": "Your box keeps working in the background.",
    "empty": "No cameras set up yet",
    "empty_hint": "Ask your installer to add the cameras for this home.",
    "loading": "Checking your box...",
    "error": "Box status is unavailable",
    "error_hint": "Check this box's setup. We'll try again automatically.",
    "activity": "Recent activity",
    "activity_empty": "No recent activity yet",
    "details": "Show details",
    "close_hint": "Closing this window keeps your home protected.",
    "saved": "Clip saved from {camera}",
    "sent": "{count} files sent to the online folder",
    "moved": "{count} clips ready for the online folder",
    "restart": "Home Guard restarted",
    "upload_error": "The online folder needs attention",
    "warning": "Your box needs attention",
    "reconnect": "Camera is reconnecting",
    "setup": "Set up a home",
    "simulation": "Practice setup / No box will be changed",
    "next": "Continue",
    "back": "Back",
    "start": "Start practice setup",
    "finish": "Done",
    "retry": "Try again",
    "validation": "Check the highlighted information before continuing.",
    "address_title": "Let's connect your box",
    "address_hint": "Use the box address provided during its first setup.",
    "address": "Box address (user@address)",
    "network_title": "Connect to the home network",
    "network_hint": "Choose the same network that the home's cameras use.",
    "ethernet": "Ethernet cable",
    "wifi": "Wi-Fi",
    "ssid": "Network name",
    "wifi_password": "Network password",
    "house_title": "Make this box feel at home",
    "house_hint": "Give the home a short name using lowercase letters, numbers or underscores.",
    "house": "House name",
    "show": "Show camera pictures on the box",
    "alerts": "Turn on security alerts",
    "hours": "Alert hours (0-23)",
    "camera_title": "Find the home's cameras",
    "camera_hint": "Use the camera or recorder login. You can also do this later.",
    "find": "Find cameras during setup",
    "camera_user": "Camera login name",
    "camera_password": "Camera password",
    "failure": "Practice a network failure",
    "progress_title": "Getting everything ready",
    "progress_hint": "Keep the box powered on while these steps finish.",
    "update": "Update software",
    "name_step": "Set house name and screen preferences",
    "network_step": "Save network and rescue hotspot",
    "camera_step": "Find cameras",
    "readiness": "Check readiness",
    "pending": "Waiting",
    "running": "Working...",
    "PASS": "PASS",
    "WARN": "WARN",
    "FAIL": "FAIL",
    "updated": "Software is up to date",
    "named": "Home preferences saved",
    "network_ok": "Home network and rescue hotspot saved",
    "network_cable_fail": "The box could not reach the home network. Check the cable and router, then try again.",
    "network_fail": "Could not join the home network. Check the network name and password, then try again.",
    "found": "3 cameras found",
    "skipped": "Find cameras later at the customer's home",
    "ready": "Collector and online folder are ready",
    "summary_title": "Setup finished",
    "summary_hint": "Practice complete. Nothing was changed on a real box.",
    "failed_title": "Setup needs your attention",
    "manual": "Before you leave",
    "manual_items": "1. Set power recovery in the box's BIOS to Power On.\n2. Disable access-key expiry in the Tailscale admin console.\n3. Remove the installer's saved Wi-Fi before delivery.\n4. Check camera coverage with the homeowner.",
    "rescue": "Rescue hotspot",
    "rescue_hint": "If the home network changes, use a phone hotspot to recover the box.",
    "rescue_demo": "Practice only / hotspot details will be supplied by the real setup service.",
    "steps": "CONNECT   /   NETWORK   /   HOME   /   CAMERAS   /   READY",
    "camera_count": "{count} cameras",
    "demo_address": "installer@box.example",
    "demo_site": "cedar_house",
    "demo_ssid": "Home network",
    "demo_user": "installer",
    "demo_house": "Cedar House",
    "demo_camera": "Camera {number}",
    "demo_names": [
        "Front door",
        "Garden",
        "Driveway",
        "Side gate",
        "Patio",
        "Garage",
        "Back door",
        "Porch",
        "Courtyard",
    ],
    "demo_events": [
        "Clip saved from front door",
        "13 clips sent",
        "Home Guard restarted",
    ],
    "demo_details": [
        "14:32:10 INFO [front_door] trigger saved: local clip",
        "2026-10-02 14:31:02 INFO Done. Uploaded: 13 | Failed: 0",
        "2026-10-02 14:29:00 Starting data_collection",
    ],
    "demo_time": "Today, 14:32",
    "gb": "{value:.1f} GB",
    "unknown": "Unavailable",
    "page": "Step {number} of 4",
    "status_rows": "Readiness report",
    "check_collector": "Background collection is ready",
    "check_network": "Home network is ready",
    "check_folder": "Online folder access is ready",
    "check_power": "Check power recovery and sleep settings by hand",
    "ready_warn": "Essential checks passed; check power settings by hand",
    "rescue_name": "Hotspot name",
    "rescue_password": "Hotspot password",
    "service_pending": "Supplied after real setup",
    "separator": " / ",
    "bullet": "-  ",
    "hidden_address": "[address hidden]",
    "hidden": "[hidden]",
    "camera_later": "Find the cameras at the customer's home before delivery.",
}


TEXT.update({
 "failure_cameras_title": "No cameras found",
 "failure_login_title": "This login was refused by {count} of {total} devices",
 "failure_location": "The box is on the Wi-Fi {network} ({address})",
 "failure_location_unknown": "Nothing on the box's network answers as a camera",
 "failure_cameras_body": "{location}. Usually the recorder is off or plugged into a different router. Check its power and that it shares the box's home network, then search again.",
 "failure_network_title": "The box did not come back on {network}",
 "failure_home_network": "the home network",
 "failure_network_body": "The box may still be joining the network. Check the Wi-Fi name and password, and keep the box powered on. If it stays offline, use the rescue Wi-Fi to reconnect.",
 "failure_connect_title": "The box did not answer",
 "failure_connect_body": "Check that the box is powered on and connected to the internet. Open Tailscale on this computer and the box, then check the address and Windows user name.",
 "failure_update_title": "The box software could not be updated",
 "failure_update_body": "The box needs an internet connection to download its software. Check the connection, then try again. Your answers are kept.",
 "failure_other_title": "Setup needs your attention",
 "failure_other_body": "Check the box's connection, then try again. Your answers are kept.",
 "search_again": "Search again", "change_camera_login": "Change the camera login",
 "finish_without_cameras": "Finish without cameras", "show_readable_details": "Show details",
 "retry_setup_action": "Try again",
})

TEXT.update({
 "open_home_guard": "Open Home Guard", "no_cameras": "No cameras yet",
 "no_cameras_hint": "Add your cameras when you're ready. Home Guard is open and ready to set them up.",
 "find_cameras_action": "Find cameras", "box_unreachable": "The box is not reachable",
 "box_unreachable_hint": "Last known address: {address}\nCheck that the box is powered on and Tailscale is connected on both computers.",
 "no_known_address": "No box selected yet", "offline_controls": "Reconnect to the box to use this control.",
 "offline_settings": "These settings are available to read. Reconnect to the box before saving changes.",
 "zero_cameras_summary": "0 cameras — add them later from the Cameras page",
 "summary_camera_count": "{count} cameras", "summary_network": "Home network · {network}",
 "camera_search_title": "Find your cameras", "camera_search_hint": "Keep the recorder powered on and on the same network as this box. Use the camera login set when it was installed.",
 "camera_search_user": "Camera user name", "camera_search_password": "Camera password",
 "camera_search_working": "Searching the home network for cameras…", "camera_search_empty": "No cameras answered. Check the recorder's power and home network, then try again.",
 "camera_search_error": "The camera search could not finish. Check the network and camera login, then try again.",
 "failure_cameras_body": "{location}, and nothing on that network answers as a camera. Usually the recorder is off or plugged into a different router. Check its power and that it shares the box's home network, then search again.",
})

TEXT.update(ready_for_cameras="Ready for your cameras", finishing_without_cameras="Finishing setup without cameras. Confirming the earlier steps, then checking that the box is ready.")

TEXT.update(details_steps="Setup steps", hide_details="Hide details", details_working_time="Working · {seconds} s", details_finished="Finished", details_finished_warning="Finished", details_failed="Failed", details_skipped="Skipped")

TEXT.update(follow_progress="Follow progress", details_running_hint="Setup is working on this step.", details_not_started="This step has not started.", details_working="Working…", details_copied="Copied")

TEXT.update(demo_setup_connect="Checking the connection to the box.", demo_setup_update="Updating the box software.", demo_setup_site="Saving your house name and preferences.", demo_setup_network="Preparing the home network.", demo_setup_cameras="Searching for cameras on the home network.", demo_setup_alerts="Saving your alert hours.", demo_setup_readiness="Checking that Home Guard is ready.")

TEXT.update(detail_no_camera_answer="No cameras answered on the home network. Check the recorder's power and network cable.")

TEXT.update(summary_details_heading="Setup finished · {house}")

TEXT.update(show_detections="Show detections on the pictures",show_detections_tooltip="Show detections (D)",display_group="Display",detection_labels="Detection labels",labels_confidence="Name and confidence",labels_name="Name only",labels_none="None",viewer_save_error="The display preference could not be saved.")

TEXT.update(live_applied="Applied",detection_group="Detection",sensitivity="Sensitivity",certainty_required="Needs to be {percent}% sure",more_alerts="More alerts",fewer_false_alarms="Fewer false alarms",reset_sensitivity="Reset to 40%",live_not_picked_up="The program has not picked this up yet",sensitivity_in_force="Sensitivity {percent}%")

TEXT.update(camera_off="Off")

TEXT.update(quiet_status="Last upload {time} \u00b7 {clips} clips waiting \u00b7 {disk} GB free")

TEXT.update(today="Today",quiet_group="Checked {camera} {count} times since {time} \u2014 {text}",quiet_once="Checked {camera} \u00b7 {time} \u2014 {text}",quiet_paused_group="{camera} \u00b7 Alerts paused \u00b7 {count} checks since {time}",quiet_paused_once="{camera} \u00b7 Alerts paused \u00b7 {time}",quiet_no_alert="{text}; no alert",demo_pause_summary="Alerts are paused; the AI was not asked.")

TEXT.update({"demo_chat_hebrew_answer": "\u05d1\u05d5\u05d5\u05d3\u05d0\u05d9. \u05d0\u05de\u05e9\u05d9\u05da \u05dc\u05e9\u05de\u05d5\u05e8 \u05e2\u05dc \u05d4\u05d1\u05d9\u05ea.", "demo_chat_arabic": "\u0647\u0644 \u0627\u0644\u0628\u064a\u062a \u0628\u0623\u0645\u0627\u0646\u061f", "demo_chat_arabic_answer": "\u0646\u0639\u0645\u060c \u0623\u0646\u0627 \u0623\u0631\u0627\u0642\u0628 \u0627\u0644\u0643\u0627\u0645\u064a\u0631\u0627\u062a."})

TEXT.update(quiet_paused_description="{text}; alerts paused")

def tr(key, **values):
    return TEXT[key].format(**values)
