"""All visible application copy; keys remain stable for translation."""

TEXT = {
    "detection_label": "{label} {percent}%",
    "detector_sees": "Sees: {objects}",
    "object_count": "{count} {label}",
    "object_person": "person", "object_person_plural": "people",
    "object_car": "car", "object_car_plural": "cars",
    "object_truck": "truck", "object_truck_plural": "trucks",
    "object_bus": "bus", "object_bus_plural": "buses",
    "object_bicycle": "bicycle", "object_bicycle_plural": "bicycles",
    "object_motorcycle": "motorcycle", "object_motorcycle_plural": "motorcycles",
    "detector_nothing": "Nothing right now",
    "detector_not_looking": "Detector is not looking at this camera",

    "camera_search_wait": "Looking for cameras. Some devices may take a few minutes to answer.",
    "camera_search_elapsed": "Searching - {minutes}m {seconds}s",

    "camera_changes_save_failed": "The camera changes could not be saved. Check the camera names and try again.",
    "camera_setup_finished": "Setup finished - {house}\n{count} cameras found: {names}",
    "camera_none_found": "None found",
    "camera_check_only_hint": "Camera check only. Setup will not be run.",
    "camera_photos_load_failed": "The camera photos could not be loaded",
    "camera_save_failed": "The camera changes could not be saved. Your setup is still complete.",
    "skip_camera_check": "Skip the camera check",
    "only_check_cameras": "Only check this box's cameras",

    "detail_camera_refused_count": "{count} of {total} cameras refused the login.",
    "detail_recorder_answers": "{count} cameras answer on the recorder.",
    "detail_channel_ok": "Camera {channel} sent a picture ({size}).",
    "detail_channel_no_picture": "Camera {channel} answers, but no picture arrived.",
    "detail_device_skipped": "A device did not answer and was skipped.",
    "detail_camera_found": "Camera found: {name} ({size}).",

    "demo_box_name": "Home Guard box",
    "box_label": "The box",
    "box_loading": "Looking for Windows boxes on this laptop's Tailscale network...",
    "box_address_placeholder": "Box address, for example 100.100.100.10",
    "box_user_label": "Windows user name on the box",
    "box_user_help": "The Windows account on the box. On the box, open Command Prompt and type whoami; it is the part after the backslash.",
    "box_manual": "Type an address",
    "box_peer": "{name} - {address}",
    "box_offline": " (offline)",
    "box_pick_hint": "Choose the customer's box by name, or type its address.",
    "box_address_help": "On this laptop, open Tailscale and copy the address of the customer's box.",
    "box_target_error": "Enter the box address and its Windows user name (letters, digits, underscores, dots or hyphens).",

    "camera_login_help": "The user name is usually admin. Use the password set when the cameras were installed, the recorder's admin password, or the code on the camera label.",
    "camera_lock_warning": "Before trying a third time: some cameras lock logins for a while after repeated failures. Check the password before continuing.",
    "retry_confirming": "Confirming the earlier steps, then trying the new camera login.",
    "technical_log": "Technical log",
    "copy_log": "Copy",
    "details_empty": "No additional notes for this step yet.",
    "detail_login_refused": "A camera refused this login. Check its user name and password.",
    "detail_timeout": "A camera did not send a picture in time. Check its power and connection.",
    "detail_no_stream": "No working picture address was found for a camera.",
    "detail_try_stream": "Trying another picture address for a camera.",
    "detail_find_cameras": "Looking for cameras on the home network.",
    "detail_update": "Updating the software on the box.",
    "detail_copy": "Copying setup files to the box.",
    "detail_command": "Running a setup command on the box.",

    "camera_check_pending": "Finish loading the camera check before continuing. If it failed, refresh the photos and try again.",

    "setup_window_title": "Home Guard Setup",
    "address_not_remembered": "The box address could not be remembered. Enter it again next time.",

    "check_cameras_title": "Check the cameras",
    "check_cameras_hint": "Confirm the views, names and enabled cameras, or skip this check and finish.",
    "camera_snapshot_failed": "Could not take a photo. Check camera power and connection, then refresh.",
    "remote_cameras_saved": "Camera changes saved on the box.",
    "camera_check_continue": "Finish setup",
    "camera_check_unsaved": "Save your camera changes before finishing setup.",

    "setup_live_hint": "Set up the box for this home. Changes begin only after you review and start setup.",
    "review_title": "Review your setup",
    "review_hint": "Check these choices before making changes to the box.",
    "review_text": "You are about to set up box {target}\n\nNetwork: {network}\nHouse: {house}\nSecurity alerts: {alerts}\nCameras: {cameras}",
    "alerts_on_review": "On - {hours}; {minutes:g} minutes between alerts",
    "alerts_off_review": "Off - save clips only",
    "cameras_find_review": "Find and check the cameras",
    "cameras_later_review": "Set up cameras later",
    "start_setup": "Start setup",
    "powershell_missing": "Windows PowerShell is missing. Install it, then try again.",
    "engine_missing": "The setup program is missing. Restore the Home Guard setup folder, then try again.",
    "engine_launch_error": "The setup program could not run. Check that it is installed, then try again.",
    "engine_incomplete": "Setup ended before every step finished. Check the box connection and try again.",
    "engine_protocol_error": "The setup program reported steps out of order. Update the setup program and try again.",
    "setup_step_complete": "Finished",
    "setup_elapsed": "Working - {seconds}s",
    "cancel_setup": "Cancel setup",
    "setup_cancelled": "Setup cancelled. Changes already made on the box may remain.",
    "live_summary_hint": "Setup finished. Complete the checks below before leaving.",
    "step_connect": "Connect to the box",
    "step_update": "Update software",
    "step_site": "Save home preferences",
    "step_network": "Connect the home network",
    "step_cameras": "Find cameras",
    "step_alerts": "Set security alerts",
    "step_readiness": "Check readiness",
    "step_skip": "Skipped",

    "address_error": "Enter a box address like installer@box.example.",
    "ssid_error": "Enter the home Wi-Fi network name.",
    "wifi_password_error": "Enter a network password with 8 to 63 characters.",
    "house_error": "Use lowercase letters, numbers and underscores, like cedar_house.",
    "camera_user_error": "Enter the login name used by the cameras.",
    "camera_password_error": "Enter the password used by the cameras.",
    "step_names": ["Connect", "Network", "Home", "Cameras", "Ready"],
    "step_number": "{number}. {name}",
    "step_done": "\u2713 {name}",
    "event_line": "{time}  {text}",
    "time_unavailable": "Time unavailable",

    "summary_house": "Home: {house}",
    "enlarge_hint": "Click a camera to enlarge it. Click again or press Esc to return.",

    "stopped_banner": "Home Guard is stopped. Your home is not being watched.",
    "close_stopped": "Home Guard is stopped. Start it to watch your home again.",
    "close_starting": "Home Guard is starting. Watching has not resumed yet.",
    "all_day_choice": "All day",
    "hours_from": "From",
    "hours_to": "To",
    "watching": "Watching",
    "paused_until": "Alerts paused until {time}",
    "paused_some": "Some camera alerts paused until {time}",
    "resume_alerts": "Resume alerts",

    "cameras_title": "Your cameras",
    "cameras_hint": "Choose which cameras protect your home. Use lowercase letters, numbers and underscores for names. Refreshing photos may take a few moments per camera.",
    "refresh_photos": "Refresh photos",
    "save_cameras": "Save cameras",
    "camera_working": "Working on your cameras...",
    "camera_ready": "Photos loaded. Make your changes, then save.",
    "camera_saved": "Camera changes saved. The box is applying them.",
    "camera_error": "We could not finish. Check your cameras and try again.",
    "camera_empty": "No cameras are configured for this box yet.",
    "camera_no_photo": "No picture available",
    "camera_enabled": "Enabled",
    "camera_name": "Camera name",
    "camera_names_invalid": "Give every camera a different name using lowercase letters, numbers and underscores.",
    "cameras_page": "Cameras",

    "overview": "Overview",
    "settings": "Settings",
    "settings_title": "How Home Guard protects your home",
    "settings_hint": "Changes apply to this box. Your cameras keep their existing login details.",
    "security_alerts": "Security alerts",
    "security_alerts_hint": "On: watch the home and send alerts. Off: only save camera clips.",
    "alert_from": "Alerts from (hour)",
    "alert_until": "Alerts until (hour)",
    "all_day": "Alerts can arrive all day.",
    "hours_window": "Alerts from {start:02d}:00 until {end:02d}:00.",
    "hours_overnight": "Alerts from {start:02d}:00 tonight until {end:02d}:00 tomorrow.",
    "cooldown": "Minutes between alerts from the same camera",
    "minutes_suffix": " minutes",
    "cooldown_hint": "From 10 seconds to 24 hours. Times are saved to the nearest second.",
    "save_settings": "Save settings",
    "settings_saved": "Saved.",
    "saved_stopped": "Saved. Choose Start Home Guard to use these settings.",
    "applying": "Applying settings - Home Guard is restarting...",
    "restarting": "Restarting",
    "applying_hint": "Your new settings are saved. Waiting for Home Guard to start again.",
    "apply_slow": "Still waiting for Home Guard. Check that the box is running.",
    "applied": "Settings applied. Home Guard is running.",
    "stop_box": "Stop Home Guard",
    "start_box": "Start Home Guard",
    "stop_confirm": "Stop protecting this home?",
    "stop_explanation": "Camera recording and security alerts will stop. Home Guard stays stopped, even after a restart, until you choose Start Home Guard.",
    "keep_running": "Keep running",
    "stopped_title": "Home Guard is stopped",
    "stopped_hint": "Recording and alerts are off. Choose Start Home Guard to protect this home again.",
    "start_pending": "Starting Home Guard...",
    "control_error": "The change could not be saved. Please try again.",
    "step_error": "This step could not finish. Check the box and try again.",
    "date_format": "%d %b, %H:%M",
    "brand": "HOME GUARD",
    "home": "Your home, in view.",
    "demo": "DEMONSTRATION",
    "collecting": "Collecting",
    "stopped": "Stopped",
    "collection": "Saving clips",
    "inference": "Security alerts",
    "upload": "Last upload",
    "waiting": "Clips waiting",
    "disk": "Disk free",
    "never": "No upload yet",
    "cameras": "Cameras",
    "live": "LIVE",
    "offline": "No picture",
    "offline_hint": "Waiting for a fresh picture",
    "pictures_off": "Camera pictures are switched off",
    "pictures_hint": "Your box keeps working in the background.",
    "empty": "No cameras set up yet",
    "empty_hint": "Ask your installer to add the cameras for this home.",
    "loading": "Checking your box...",
    "error": "Box status is unavailable",
    "error_hint": "Check this box's setup. We'll try again automatically.",
    "activity": "Recent activity",
    "activity_empty": "No recent activity yet",
    "details": "Show details",
    "close_hint": "Closing this window keeps your home protected.",
    "saved": "Clip saved from {camera}",
    "sent": "{count} files sent to the online folder",
    "moved": "{count} clips ready for the online folder",
    "restart": "Home Guard restarted",
    "upload_error": "The online folder needs attention",
    "warning": "Your box needs attention",
    "reconnect": "Camera is reconnecting",
    "setup": "Set up a home",
    "simulation": "Practice setup / No box will be changed",
    "next": "Continue",
    "back": "Back",
    "start": "Start practice setup",
    "finish": "Done",
    "retry": "Try again",
    "validation": "Check the highlighted information before continuing.",
    "address_title": "Let's connect your box",
    "address_hint": "Use the box address provided during its first setup.",
    "address": "Box address (user@address)",
    "network_title": "Connect to the home network",
    "network_hint": "Choose the same network that the home's cameras use.",
    "ethernet": "Ethernet cable",
    "wifi": "Wi-Fi",
    "ssid": "Network name",
    "wifi_password": "Network password",
    "house_title": "Make this box feel at home",
    "house_hint": "Give the home a short name using lowercase letters, numbers or underscores.",
    "house": "House name",
    "show": "Show camera pictures on the box",
    "alerts": "Turn on security alerts",
    "hours": "Alert hours (0-23)",
    "camera_title": "Find the home's cameras",
    "camera_hint": "Use the camera or recorder login. You can also do this later.",
    "find": "Find cameras during setup",
    "camera_user": "Camera login name",
    "camera_password": "Camera password",
    "failure": "Practice a network failure",
    "progress_title": "Getting everything ready",
    "progress_hint": "Keep the box powered on while these steps finish.",
    "update": "Update software",
    "name_step": "Set house name and screen preferences",
    "network_step": "Save network and rescue hotspot",
    "camera_step": "Find cameras",
    "readiness": "Check readiness",
    "pending": "Waiting",
    "running": "Working...",
    "PASS": "PASS",
    "WARN": "WARN",
    "FAIL": "FAIL",
    "updated": "Software is up to date",
    "named": "Home preferences saved",
    "network_ok": "Home network and rescue hotspot saved",
    "network_cable_fail": "The box could not reach the home network. Check the cable and router, then try again.",
    "network_fail": "Could not join the home network. Check the network name and password, then try again.",
    "found": "3 cameras found",
    "skipped": "Find cameras later at the customer's home",
    "ready": "Collector and online folder are ready",
    "summary_title": "Setup finished",
    "summary_hint": "Practice complete. Nothing was changed on a real box.",
    "failed_title": "Setup needs your attention",
    "manual": "Before you leave",
    "manual_items": "1. Set power recovery in the box's BIOS to Power On.\n2. Disable access-key expiry in the Tailscale admin console.\n3. Remove the installer's saved Wi-Fi before delivery.\n4. Check camera coverage with the homeowner.",
    "rescue": "Rescue hotspot",
    "rescue_hint": "If the home network changes, use a phone hotspot to recover the box.",
    "rescue_demo": "Practice only / hotspot details will be supplied by the real setup service.",
    "steps": "CONNECT   /   NETWORK   /   HOME   /   CAMERAS   /   READY",
    "camera_count": "{count} cameras",
    "demo_address": "installer@box.example",
    "demo_site": "cedar_house",
    "demo_ssid": "Home network",
    "demo_user": "installer",
    "demo_house": "Cedar House",
    "demo_camera": "Camera {number}",
    "demo_names": [
        "Front door",
        "Garden",
        "Driveway",
        "Side gate",
        "Patio",
        "Garage",
        "Back door",
        "Porch",
        "Courtyard",
    ],
    "demo_events": [
        "Clip saved from front door",
        "13 clips sent",
        "Home Guard restarted",
    ],
    "demo_details": [
        "14:32:10 INFO [front_door] trigger saved: local clip",
        "2026-10-02 14:31:02 INFO Done. Uploaded: 13 | Failed: 0",
        "2026-10-02 14:29:00 Starting data_collection",
    ],
    "demo_time": "Today, 14:32",
    "gb": "{value:.1f} GB",
    "unknown": "Unavailable",
    "page": "Step {number} of 4",
    "status_rows": "Readiness report",
    "check_collector": "Background collection is ready",
    "check_network": "Home network is ready",
    "check_folder": "Online folder access is ready",
    "check_power": "Check power recovery and sleep settings by hand",
    "ready_warn": "Essential checks passed; check power settings by hand",
    "rescue_name": "Hotspot name",
    "rescue_password": "Hotspot password",
    "service_pending": "Supplied after real setup",
    "separator": " / ",
    "bullet": "-  ",
    "hidden_address": "[address hidden]",
    "hidden": "[hidden]",
    "camera_later": "Find the cameras at the customer's home before delivery.",
}


def tr(key, **values):
    return TEXT[key].format(**values)
