"""The app's copy in Hebrew: the same keys as strings.TEXT, in the map editor's voice (short, plain, warm).

``strings.set_language("he")`` lays these over the English ones; a key missing here would read in English, and a
test keeps the two in step.
"""

TEXT_HE = {
    "chat_image_unavailable": "התמונה לא זמינה",
    "premium_security": "אבטחה והתראות",
    "premium_viewing": "צפייה במצלמות",
    "premium_view_hint": "להסתיר את תמונות המצלמות במסך הזה. Home Guard ממשיך לשמור על הבית.",

    "premium_live": "שידור חי",
    "premium_home": "HOME GUARD / {house}",
    "premium_protecting": "שומרים על הבית",
    "premium_collecting": "מקליטים את הבית",
    "ai_assistant": "העוזר החכם",
    "ai_thinking": "העוזר מסתכל על {camera}…",
    "ai_watching": "צופה ב-{count} מצלמות",
    "ai_quiet_line": "העוזר בדק את {camera}: {text} - בלי התראה",
    "chat_button": "{name}: {text}",
    "chat_meta": "{name}   {time}",
    "chat_delivered": "נשלח למשפחה",
    "chat_refused": "לא נמסר",
    "demo_chat_alert": "מישהו מחכה ליד דלת הכניסה. נראה שהוא מביא משלוח.",
    "demo_chat_owner": "זה המשלוח שלנו. יש עוד מישהו בחוץ?",
    "demo_chat_answer": "אני רואה רק את השליח ליד הדלת. השביל פנוי.",
    "demo_chat_hebrew": "אני בבית, אפתח לו את הדלת.",
    "demo_chat_button": "התראת שווא",
    "demo_chat_maya": "תמשיך לשמור על הגינה בזמן שאנחנו אוכלים ארוחת ערב.",
    "demo_chat_answer2": "בטח. אמשיך לשמור על הגינה ואעדכן אם מישהו מתקרב.",

    "ai_delivery_banner": "ההתראות לא מגיעות לטלגרם",
    "ai_activity": "פעילות העוזר",
    "ai_sent": "התראה נשלחה",
    "ai_urgent_sent": "התראה דחופה נשלחה",
    "ai_training": "בלי התראה - לא קורה כלום (נשמר ללמידה)",
    "ai_muted": "לא נשלח - ההתראות מושהות",
    "ai_not_sent": "לא נשלח",
    "ai_empty": "עוד אין פעילות. כשמצלמה תראה אדם או רכב, התשובה של העוזר תופיע כאן.",
    "ai_stopped": "Home Guard כבוי",
    "ai_not_updating": "מצב העוזר לא מתעדכן",
    "ai_record_meta": "{time} | {camera} | {labels}",
    "ai_no_summary": "לא נשמר תיאור.",
    "ai_no_error": "לא נשמרה סיבה לכך שההתראה לא נמסרה. כדאי לבדוק את החיבור לטלגרם.",
    "demo_ai_person": "אדם הולך בשביל לכיוון דלת הכניסה.",
    "demo_ai_cars": "כמה מכוניות חונות בחניה. שום דבר לא זז.",
    "demo_ai_paused": "אדם עומד ליד שער הגינה.",
    "demo_ai_urgent": "שני אנשים מנסים לפרוץ את דלת הכניסה.",
    "demo_ai_refused": "הבוט לא חבר בקבוצה. צריך להוסיף אותו שוב לקבוצת הטלגרם.",

    "detection_label": "{label} · {percent}%",
    "detector_sees": "רואה: {objects}",
    "object_count": "{count} {label}",
    "object_person": "אדם", "object_person_plural": "אנשים",
    "object_car": "מכונית", "object_car_plural": "מכוניות",
    "object_truck": "משאית", "object_truck_plural": "משאיות",
    "object_bus": "אוטובוס", "object_bus_plural": "אוטובוסים",
    "object_bicycle": "אופניים", "object_bicycle_plural": "אופניים",
    "object_motorcycle": "אופנוע", "object_motorcycle_plural": "אופנועים",
    "detector_nothing": "כרגע לא רואים כלום",
    "detector_not_looking": "הזיהוי לא מסתכל על המצלמה הזאת",

    "camera_search_wait": "מחפשים מצלמות. חלק מהמכשירים עונים רק אחרי כמה דקות.",
    "camera_search_elapsed": "מחפשים - {minutes} דק' {seconds} שנ'",

    "camera_changes_save_failed": "לא הצלחנו לשמור את השינויים במצלמות. נסו שוב.",
    "camera_setup_finished": "ההתקנה הסתיימה - {house}\nנמצאו {count} מצלמות: {names}",
    "camera_none_found": "לא נמצאו",
    "camera_check_only_hint": "רק בדיקת מצלמות. ההתקנה לא תרוץ.",
    "camera_photos_load_failed": "לא הצלחנו לטעון את התמונות מהמצלמות",
    "camera_save_failed": "לא הצלחנו לשמור את השינויים במצלמות. ההתקנה עצמה הושלמה.",
    "skip_camera_check": "לדלג על בדיקת המצלמות",
    "only_check_cameras": "רק לבדוק את המצלמות של הקופסה הזאת",

    "detail_camera_refused_count": "{count} מתוך {total} מצלמות לא קיבלו את הכניסה.",
    "detail_recorder_answers": "{count} מצלמות עונות דרך המקליט.",
    "detail_channel_ok": "מצלמה {channel} שלחה תמונה ({size}).",
    "detail_channel_no_picture": "מצלמה {channel} עונה, אבל לא הגיעה תמונה.",
    "detail_device_skipped": "מכשיר אחד לא ענה ודילגנו עליו.",
    "detail_camera_found": "נמצאה מצלמה: {name} ({size}).",

    "demo_box_name": "קופסת Home Guard",
    "box_label": "הקופסה",
    "box_loading": "מחפשים קופסאות ברשת ה-Tailscale של המחשב הזה...",
    "box_address_placeholder": "כתובת הקופסה, למשל 100.100.100.10",
    "box_user_label": "שם המשתמש ב-Windows של הקופסה",
    "box_user_help": "חשבון ה-Windows שעל הקופסה. בקופסה, פותחים Command Prompt וכותבים whoami; זה החלק שאחרי הלוכסן.",
    "box_password": "סיסמת ה-Windows של הקופסה",
    "box_password_help": "כך הקופסה נכנסת לבד אחרי הפסקת חשמל, וחלון Home Guard חוזר בלי מקלדת. אפשר להשאיר ריק אם הקופסה כבר נכנסת לבד.",
    "box_manual": "להקליד כתובת",
    "box_peer": "{name} - {address}",
    "box_offline": " (לא מחוברת)",
    "box_pick_hint": "בחרו את הקופסה של הלקוח לפי השם, או הקלידו את הכתובת שלה.",
    "box_address_help": "במחשב הזה, פתחו את Tailscale והעתיקו את הכתובת של הקופסה של הלקוח.",
    "box_target_error": "הקלידו את כתובת הקופסה ואת שם המשתמש שלה ב-Windows (אותיות, ספרות, קו תחתון, נקודה או מקף).",

    "camera_login_help": "שם המשתמש הוא בדרך כלל admin. הסיסמה היא זו שנקבעה כשהמצלמות הותקנו, סיסמת המנהל של המקליט, או הקוד שעל המדבקה של המצלמה.",
    "camera_lock_warning": "לפני ניסיון שלישי: חלק מהמצלמות ננעלות לזמן מה אחרי כמה כישלונות. בדקו את הסיסמה לפני שממשיכים.",
    "retry_confirming": "מאשרים את השלבים הקודמים, ואז מנסים את פרטי הכניסה החדשים למצלמות.",
    "technical_log": "יומן טכני",
    "copy_log": "העתקה",
    "details_empty": "עוד אין הערות לשלב הזה.",
    "detail_login_refused": "מצלמה לא קיבלה את פרטי הכניסה. בדקו את שם המשתמש והסיסמה.",
    "detail_timeout": "מצלמה לא שלחה תמונה בזמן. בדקו את החשמל והחיבור שלה.",
    "detail_no_stream": "לא נמצאה כתובת תמונה שעובדת לאחת המצלמות.",
    "detail_try_stream": "מנסים כתובת תמונה אחרת לאחת המצלמות.",
    "detail_find_cameras": "מחפשים מצלמות ברשת של הבית.",
    "detail_update": "מעדכנים את התוכנה בקופסה.",
    "detail_copy": "מעתיקים את קבצי ההתקנה לקופסה.",
    "detail_command": "מריצים פקודת התקנה בקופסה.",

    "camera_check_pending": "חכו שבדיקת המצלמות תסיים להיטען. אם היא נכשלה, רעננו את התמונות ונסו שוב.",

    "setup_window_title": "התקנת Home Guard",
    "address_not_remembered": "לא הצלחנו לזכור את כתובת הקופסה. תצטרכו להקליד אותה שוב בפעם הבאה.",

    "check_cameras_title": "בדיקת המצלמות",
    "check_cameras_hint": "בדקו את התמונות ואילו מצלמות פועלות, או דלגו על הבדיקה וסיימו.",
    "camera_snapshot_failed": "לא הצלחנו לצלם תמונה. בדקו את החשמל והחיבור של המצלמה, ואז רעננו.",
    "remote_cameras_saved": "השינויים במצלמות נשמרו בקופסה.",
    "camera_check_continue": "לסיים את ההתקנה",
    "camera_check_unsaved": "שמרו את השינויים במצלמות לפני שמסיימים את ההתקנה.",

    "setup_live_hint": "מתקינים את הקופסה לבית הזה. שום דבר לא משתנה לפני שבודקים ומתחילים.",
    "review_title": "בדיקה לפני ההתקנה",
    "review_hint": "בדקו את הבחירות לפני שמשנים משהו בקופסה.",
    "review_text": "עומדים להתקין את הקופסה {target}\n\nרשת: {network}\nבית: {house}\nהתראות אבטחה: {alerts}\nמצלמות: {cameras}",
    "alerts_on_review": "פועלות - {hours}; {minutes:g} דקות בין התראות",
    "alerts_off_review": "כבויות - רק שמירת קטעים",
    "cameras_find_review": "למצוא ולבדוק את המצלמות",
    "cameras_later_review": "להגדיר מצלמות אחר כך",
    "start_setup": "להתחיל התקנה",
    "powershell_missing": "חסר Windows PowerShell. התקינו אותו ונסו שוב.",
    "engine_missing": "תוכנת ההתקנה חסרה. החזירו את תיקיית ההתקנה של Home Guard ונסו שוב.",
    "engine_launch_error": "תוכנת ההתקנה לא הצליחה לרוץ. בדקו שהיא מותקנת ונסו שוב.",
    "engine_incomplete": "ההתקנה נעצרה לפני שכל השלבים הסתיימו. בדקו את החיבור לקופסה ונסו שוב.",
    "engine_protocol_error": "תוכנת ההתקנה דיווחה על שלבים בסדר לא נכון. עדכנו אותה ונסו שוב.",
    "setup_step_complete": "הסתיים",
    "setup_elapsed": "עובדים - {seconds} שנ'",
    "cancel_setup": "לבטל את ההתקנה",
    "setup_cancelled": "ההתקנה בוטלה. ייתכן ששינויים שכבר נעשו בקופסה נשארו.",
    "live_summary_hint": "ההתקנה הסתיימה. השלימו את הבדיקות למטה לפני שעוזבים.",
    "step_connect": "התחברות לקופסה",
    "step_update": "עדכון התוכנה",
    "step_site": "שמירת העדפות הבית",
    "step_network": "חיבור לרשת של הבית",
    "step_cameras": "חיפוש מצלמות",
    "step_alerts": "הגדרת התראות אבטחה",
    "step_readiness": "בדיקת מוכנות",
    "step_skip": "דילגנו",

    "address_error": "הקלידו כתובת קופסה כמו installer@box.example.",
    "ssid_error": "הקלידו את שם רשת ה-Wi-Fi של הבית.",
    "wifi_password_error": "הקלידו סיסמת רשת של 8 עד 63 תווים.",
    "house_error": "באותיות לועזיות קטנות, ספרות וקו תחתון, למשל cedar_house.",
    "camera_user_error": "הקלידו את שם המשתמש של המצלמות.",
    "camera_password_error": "הקלידו את הסיסמה של המצלמות.",
    "step_names": ["חיבור", "רשת", "בית", "בעלים", "מצלמות", "המפה", "מוכן"],
    "step_number": "{number}. {name}",
    "step_done": "✓ {name}",
    "event_line": "{time}  {text}",
    "time_unavailable": "השעה לא ידועה",

    "summary_house": "בית: {house}",
    "enlarge_hint": "בחרו מצלמה למטה. לחיצה כפולה על התמונה הגדולה פותחת מסך מלא.",

    "stopped_banner": "Home Guard כבוי. אף אחד לא שומר על הבית.",
    "close_stopped": "Home Guard כבוי. הפעילו אותו כדי לשמור שוב על הבית.",
    "close_starting": "Home Guard עולה. השמירה עוד לא חזרה.",
    "all_day_choice": "כל היום",
    "hours_from": "מ-",
    "hours_to": "עד",
    "watching": "שומרים",
    "paused_until": "ההתראות מושהות עד {time}",
    "paused_some": "התראות של חלק מהמצלמות מושהות עד {time}",
    "resume_alerts": "להחזיר את ההתראות",

    "cameras_title": "המצלמות שלכם",
    "cameras_hint": "בחרו אילו מצלמות שומרות על הבית. רענון התמונות יכול לקחת כמה רגעים לכל מצלמה.",
    "refresh_photos": "לרענן תמונות",
    "save_cameras": "לשמור מצלמות",
    "camera_working": "עובדים על המצלמות...",
    "camera_ready": "התמונות נטענו. עשו את השינויים ושמרו.",
    "camera_saved": "השינויים במצלמות נשמרו. הקופסה מחילה אותם.",
    "camera_error": "לא הצלחנו לסיים. בדקו את המצלמות ונסו שוב.",
    "camera_empty": "עוד אין מצלמות בקופסה הזאת.",
    "camera_no_photo": "אין תמונה",
    "camera_enabled": "פועלת",
    "camera_name": "שם המצלמה",
    "camera_names_invalid": "לכל מצלמה צריך שם אחר.",
    "cameras_page": "מצלמות",

    "overview": "סקירה",
    "settings": "הגדרות",
    "settings_title": "איך Home Guard שומר על הבית",
    "settings_hint": "השינויים חלים על הקופסה הזאת. פרטי הכניסה של המצלמות לא משתנים.",
    "security_alerts": "התראות אבטחה",
    "security_alerts_hint": "פועל: שומרים על הבית ושולחים התראות. כבוי: רק שומרים קטעים מהמצלמות.",
    "alert_from": "התראות משעה",
    "alert_until": "התראות עד שעה",
    "all_day": "התראות יכולות להגיע כל היום.",
    "hours_window": "התראות מ-{start:02d}:00 עד {end:02d}:00.",
    "hours_overnight": "התראות מ-{start:02d}:00 בערב עד {end:02d}:00 למחרת.",
    "cooldown": "דקות בין התראות מאותה מצלמה",
    "minutes_suffix": " דקות",
    "cooldown_hint": "מ-10 שניות ועד 24 שעות. הזמנים נשמרים בדיוק של שנייה.",
    "save_settings": "לשמור הגדרות",
    "settings_saved": "נשמר.",
    "saved_stopped": "נשמר. בחרו \"להפעיל את Home Guard\" כדי שההגדרות ייכנסו לתוקף.",
    "applying": "מחילים את ההגדרות - Home Guard עולה מחדש...",
    "restarting": "עולה מחדש",
    "applying_hint": "ההגדרות החדשות נשמרו. מחכים ש-Home Guard יעלה שוב.",
    "apply_slow": "עדיין מחכים ל-Home Guard. בדקו שהקופסה פועלת.",
    "applied": "ההגדרות נכנסו לתוקף. Home Guard פועל.",
    "stop_box": "לכבות את Home Guard",
    "start_box": "להפעיל את Home Guard",
    "stop_confirm": "להפסיק לשמור על הבית?",
    "stop_explanation": "ההקלטה וההתראות ייעצרו. Home Guard יישאר כבוי, גם אחרי הפעלה מחדש, עד שתבחרו \"להפעיל את Home Guard\".",
    "keep_running": "להמשיך לשמור",
    "stopped_title": "Home Guard כבוי",
    "stopped_hint": "ההקלטה וההתראות כבויות. בחרו \"להפעיל את Home Guard\" כדי לשמור שוב על הבית.",
    "start_pending": "מפעילים את Home Guard...",
    "control_error": "לא הצלחנו לשמור את השינוי. נסו שוב.",
    "step_error": "השלב הזה לא הסתיים. בדקו את הקופסה ונסו שוב.",
    "date_format": "%d.%m, %H:%M",
    "brand": "HOME GUARD",
    "home": "הבית שלכם, לנגד העיניים.",
    "demo": "הדגמה",
    "collecting": "אוסף",
    "stopped": "כבוי",
    "collection": "שמירת קטעים",
    "inference": "התראות אבטחה",
    "upload": "העלאה אחרונה",
    "waiting": "קטעים שמחכים",
    "disk": "מקום פנוי",
    "never": "עוד לא הועלה",
    "cameras": "מצלמות",
    "live": "שידור חי",
    "offline": "אין תמונה",
    "offline_hint": "מחכים לתמונה חדשה",
    "pictures_off": "תמונות המצלמות כבויות",
    "pictures_hint": "הקופסה ממשיכה לעבוד ברקע.",
    "empty": "עוד אין מצלמות",
    "empty_hint": "בקשו מהמתקין להוסיף את המצלמות של הבית.",
    "loading": "בודקים את הקופסה...",
    "error": "מצב הקופסה לא זמין",
    "error_hint": "בדקו את ההתקנה של הקופסה. ננסה שוב לבד.",
    "activity": "פעילות אחרונה",
    "activity_empty": "עוד אין פעילות",
    "details": "להציג פרטים",
    "close_hint": "גם כשהחלון סגור, הבית שמור.",
    "saved": "נשמר קטע מ{camera}",
    "sent": "{count} קבצים נשלחו לתיקייה ברשת",
    "moved": "{count} קטעים מוכנים לתיקייה ברשת",
    "restart": "Home Guard עלה מחדש",
    "upload_error": "התיקייה ברשת צריכה טיפול",
    "warning": "הקופסה צריכה טיפול",
    "reconnect": "המצלמה מתחברת מחדש",
    "setup": "התקנת בית",
    "simulation": "התקנת תרגול / שום קופסה לא משתנה",
    "next": "המשך",
    "back": "חזרה",
    "start": "להתחיל התקנת תרגול",
    "finish": "סיום",
    "retry": "לנסות שוב",
    "validation": "בדקו את הפרטים המסומנים לפני שממשיכים.",
    "address_title": "מתחברים לקופסה",
    "address_hint": "השתמשו בכתובת הקופסה שקיבלתם בהתקנה הראשונה שלה.",
    "address": "כתובת הקופסה (user@address)",
    "network_title": "חיבור לרשת של הבית",
    "network_hint": "בחרו את אותה רשת שהמצלמות של הבית משתמשות בה.",
    "ethernet": "כבל רשת",
    "wifi": "Wi-Fi",
    "ssid": "שם הרשת",
    "wifi_password": "סיסמת הרשת",
    "house_title": "שהקופסה תרגיש בבית",
    "house_hint": "תנו לבית שם קצר באותיות לועזיות קטנות, ספרות או קו תחתון.",
    "house": "שם הבית",
    "show": "להציג את תמונות המצלמות בקופסה",
    "alerts": "להפעיל התראות אבטחה",
    "hours": "שעות התראה (0-23)",
    "camera_title": "מוצאים את המצלמות של הבית",
    "camera_hint": "הקלידו את פרטי הכניסה של המצלמות או של המקליט. אפשר גם אחר כך.",
    "find": "למצוא מצלמות במהלך ההתקנה",
    "camera_user": "שם משתמש של המצלמות",
    "camera_password": "סיסמת המצלמות",
    "failure": "לתרגל תקלת רשת",
    "progress_title": "מכינים הכול",
    "progress_hint": "השאירו את הקופסה דולקת עד שהשלבים יסתיימו.",
    "update": "עדכון התוכנה",
    "name_step": "שמירת שם הבית והעדפות המסך",
    "network_step": "שמירת הרשת ונקודת החירום",
    "camera_step": "חיפוש מצלמות",
    "readiness": "בדיקת מוכנות",
    "pending": "מחכה",
    "running": "עובדים...",
    "PASS": "תקין",
    "WARN": "אזהרה",
    "FAIL": "נכשל",
    "updated": "התוכנה מעודכנת",
    "named": "העדפות הבית נשמרו",
    "network_ok": "רשת הבית ונקודת החירום נשמרו",
    "network_cable_fail": "הקופסה לא הגיעה לרשת של הבית. בדקו את הכבל והנתב, ונסו שוב.",
    "network_fail": "לא הצלחנו להתחבר לרשת של הבית. בדקו את שם הרשת והסיסמה, ונסו שוב.",
    "found": "נמצאו 3 מצלמות",
    "skipped": "למצוא מצלמות אחר כך, בבית של הלקוח",
    "ready": "האיסוף והתיקייה ברשת מוכנים",
    "summary_title": "ההתקנה הסתיימה",
    "summary_hint": "התרגול הסתיים. שום דבר לא השתנה בקופסה אמיתית.",
    "failed_title": "ההתקנה צריכה את תשומת הלב שלכם",
    "manual": "לפני שעוזבים",
    "manual_items": "1. ב-BIOS של הקופסה, להגדיר חזרת חשמל ל-Power On.\n2. לבטל את פקיעת מפתח הגישה במסוף הניהול של Tailscale.\n3. למחוק את ה-Wi-Fi השמור של המתקין לפני המסירה.\n4. לבדוק עם בעלי הבית מה המצלמות מכסות.",
    "rescue": "נקודת חירום",
    "rescue_hint": "אם הרשת של הבית משתנה, אפשר להחזיר את הקופסה דרך נקודה חמה מהטלפון.",
    "rescue_demo": "תרגול בלבד / פרטי הנקודה החמה יגיעו מההתקנה האמיתית.",
    "steps": "חיבור   /   רשת   /   בית   /   מצלמות   /   מוכן",
    "camera_count": "{count} מצלמות",
    "demo_address": "installer@box.example",
    "demo_site": "cedar_house",
    "demo_ssid": "הרשת של הבית",
    "demo_user": "installer",
    "demo_house": "בית הארזים",
    "demo_camera": "מצלמה {number}",
    "demo_names": [
        "Front door",
        "Garden",
        "Driveway",
        "Side gate",
        "Patio",
        "Garage",
        "Back door",
        "Porch",
        "Courtyard",
    ],
    "demo_events": [
        "נשמר קטע מדלת הכניסה",
        "13 קטעים נשלחו",
        "Home Guard עלה מחדש",
    ],
    "demo_details": [
        "14:32:10 INFO [front_door] trigger saved: local clip",
        "2026-10-02 14:31:02 INFO Done. Uploaded: 13 | Failed: 0",
        "2026-10-02 14:29:00 Starting data_collection",
    ],
    "demo_time": "היום, 14:32",
    "gb": "{value:.1f} GB",
    "unknown": "לא זמין",
    "page": "שלב {number} מתוך 4",
    "status_rows": "דוח מוכנות",
    "check_collector": "האיסוף ברקע מוכן",
    "check_network": "הרשת של הבית מוכנה",
    "check_folder": "הגישה לתיקייה ברשת מוכנה",
    "check_power": "לבדוק ביד את חזרת החשמל ואת הגדרות השינה",
    "ready_warn": "הבדיקות החשובות עברו; את הגדרות החשמל צריך לבדוק ביד",
    "rescue_name": "שם הנקודה החמה",
    "rescue_password": "סיסמת הנקודה החמה",
    "service_pending": "יגיע אחרי ההתקנה האמיתית",
    "separator": " / ",
    "bullet": "-  ",
    "hidden_address": "[הכתובת מוסתרת]",
    "hidden": "[מוסתר]",
    "camera_later": "מצאו את המצלמות בבית של הלקוח לפני המסירה.",

    "failure_cameras_title": "לא נמצאו מצלמות",
    "failure_login_title": "{count} מתוך {total} מכשירים לא קיבלו את פרטי הכניסה",
    "failure_location": "הקופסה מחוברת ל-Wi-Fi {network} ({address})",
    "failure_location_unknown": "שום דבר ברשת של הקופסה לא עונה כמו מצלמה",
    "failure_cameras_body": "{location}, ועוד אף מצלמה לא ענתה. אם הקופסה רק עכשיו הצטרפה לרשת, חכו דקה וחפשו שוב. אם עדיין אף מצלמה לא עונה, בדקו שהמקליט דולק ומחובר לאותה רשת של הבית.",
    "failure_network_title": "הקופסה לא חזרה לרשת {network}",
    "failure_home_network": "הרשת של הבית",
    "failure_network_body": "ייתכן שהקופסה עוד מתחברת לרשת. בדקו את שם ה-Wi-Fi והסיסמה, והשאירו את הקופסה דולקת. אם היא נשארת מנותקת, התחברו אליה מחדש דרך רשת החירום.",
    "failure_connect_title": "הקופסה לא ענתה",
    "failure_connect_body": "בדקו שהקופסה דולקת ומחוברת לאינטרנט. פתחו את Tailscale במחשב הזה ובקופסה, ואז בדקו את הכתובת ואת שם המשתמש ב-Windows.",
    "failure_update_title": "לא הצלחנו לעדכן את התוכנה בקופסה",
    "failure_update_body": "הקופסה צריכה חיבור לאינטרנט כדי להוריד את התוכנה. בדקו את החיבור ונסו שוב. התשובות שלכם נשמרות.",
    "failure_other_title": "ההתקנה צריכה את תשומת הלב שלכם",
    "failure_other_body": "בדקו את החיבור של הקופסה ונסו שוב. התשובות שלכם נשמרות.",
    "search_again": "לחפש שוב", "change_camera_login": "לשנות את פרטי הכניסה של המצלמות",
    "finish_without_cameras": "לסיים בלי מצלמות", "show_readable_details": "להציג פרטים",
    "retry_setup_action": "לנסות שוב",

    "open_home_guard": "לפתוח את Home Guard", "no_cameras": "עוד אין מצלמות",
    "no_cameras_hint": "הוסיפו את המצלמות כשתהיו מוכנים. Home Guard פתוח ומוכן להגדיר אותן.",
    "find_cameras_action": "למצוא מצלמות", "box_unreachable": "אין חיבור לקופסה",
    "box_unreachable_hint": "הכתובת האחרונה הידועה: {address}\nבדקו שהקופסה דולקת ושה-Tailscale מחובר בשני המחשבים.",
    "no_known_address": "עוד לא נבחרה קופסה", "offline_controls": "התחברו מחדש לקופסה כדי להשתמש בזה.",
    "offline_settings": "אפשר לקרוא את ההגדרות. התחברו מחדש לקופסה לפני ששומרים שינויים.",
    "zero_cameras_summary": "0 מצלמות - אפשר להוסיף אחר כך מעמוד המצלמות",
    "summary_camera_count": "{count} מצלמות", "summary_network": "הרשת של הבית · {network}",
    "camera_search_title": "מוצאים את המצלמות", "camera_search_hint": "השאירו את המקליט דולק ובאותה רשת כמו הקופסה. השתמשו בפרטי הכניסה של המצלמות מההתקנה שלהן.",
    "camera_search_user": "שם משתמש של המצלמות", "camera_search_password": "סיסמת המצלמות",
    "camera_search_working": "מחפשים מצלמות ברשת של הבית…", "camera_search_empty": "אף מצלמה לא ענתה. בדקו את החשמל של המקליט ואת הרשת של הבית, ונסו שוב.",
    "camera_search_error": "החיפוש לא הסתיים. בדקו את הרשת ואת פרטי הכניסה של המצלמות, ונסו שוב.",

    "ready_for_cameras": "מוכנים למצלמות שלכם",
    "finishing_without_cameras": "מסיימים את ההתקנה בלי מצלמות. מאשרים את השלבים הקודמים, ואז בודקים שהקופסה מוכנה.",
    "details_steps": "שלבי ההתקנה", "hide_details": "להסתיר פרטים", "details_working_time": "עובדים · {seconds} שנ'",
    "details_finished": "הסתיים", "details_finished_warning": "הסתיים", "details_failed": "נכשל", "details_skipped": "דילגנו",
    "follow_progress": "לעקוב אחרי ההתקדמות", "details_running_hint": "ההתקנה עובדת על השלב הזה.",
    "details_not_started": "השלב הזה עוד לא התחיל.", "details_working": "עובדים…", "details_copied": "הועתק",
    "demo_setup_connect": "בודקים את החיבור לקופסה.", "demo_setup_update": "מעדכנים את התוכנה בקופסה.",
    "demo_setup_site": "שומרים את שם הבית וההעדפות.", "demo_setup_network": "מכינים את הרשת של הבית.",
    "demo_setup_cameras": "מחפשים מצלמות ברשת של הבית.", "demo_setup_alerts": "שומרים את שעות ההתראות.",
    "demo_setup_readiness": "בודקים ש-Home Guard מוכן.",
    "detail_no_camera_answer": "אף מצלמה לא ענתה ברשת של הבית. בדקו את החשמל ואת כבל הרשת של המקליט.",
    "summary_details_heading": "ההתקנה הסתיימה · {house}",

    "show_detections": "להציג זיהויים על התמונות", "show_detections_tooltip": "להציג זיהויים (D)",
    "display_group": "תצוגה", "detection_labels": "תוויות זיהוי", "labels_confidence": "שם ורמת ביטחון",
    "labels_name": "רק שם", "labels_none": "בלי", "viewer_save_error": "לא הצלחנו לשמור את העדפת התצוגה.",
    "live_applied": "הוחל", "detection_group": "זיהוי", "sensitivity": "רגישות",
    "certainty_required": "צריך להיות בטוח ב-{percent}%", "more_alerts": "יותר התראות",
    "fewer_false_alarms": "פחות התראות שווא", "reset_sensitivity": "לחזור לערך המומלץ",
    "live_not_picked_up": "התוכנה עוד לא קלטה את זה", "sensitivity_in_force": "רגישות {percent}%",
    "camera_off": "כבויה",
    "quiet_status": "העלאה אחרונה {time} · {clips} קטעים מחכים · {disk} GB פנויים",
    "today": "היום", "quiet_group": "{camera} נבדקה {count} פעמים מאז {time} — {text}",
    "quiet_once": "{camera} נבדקה · {time} — {text}",
    "quiet_paused_group": "{camera} · ההתראות מושהות · {count} בדיקות מאז {time}",
    "quiet_paused_once": "{camera} · ההתראות מושהות · {time}",
    "quiet_no_alert": "{text}; בלי התראה", "demo_pause_summary": "ההתראות מושהות; לא שאלנו את העוזר.",
    "demo_chat_hebrew_answer": "בוודאי. אמשיך לשמור על הבית.",
    "demo_chat_arabic": "هل البيت بأمان؟",
    "demo_chat_arabic_answer": "نعم، أنا أراقب الكاميرات.",
    "quiet_paused_description": "{text}; ההתראות מושהות",

    "camera_zone_button": "לסמן את האזור לשמירה",
    "camera_zone_whole": "שומרים על: כל התמונה",
    "camera_zone_drawn": "שומרים על: האזור שסימנתם",
    "camera_zone_eyebrow": "מצלמה · {camera}",
    "camera_zone_title": "סמנו את האזור לשמירה",
    "camera_zone_help": "לחצו על הפינות של האזור שהמצלמה צריכה לשמור עליו. הקופסה מתעלמת מכל מה שמחוץ לו.",
    "camera_zone_status_empty": "שומרים על כל התמונה",
    "camera_zone_status_drawing": "הוסיפו לפחות 3 פינות",
    "camera_zone_status_closed": "שומרים על {percent} % מהתמונה",
    "camera_zone_corners": "{count} פינות",
    "camera_zone_one_corner": "פינה אחת",
    "camera_zone_small": "האזור קטן מאוד; המצלמה כמעט לא תראה כלום.",
    "camera_zone_undo": "ביטול",
    "camera_zone_clear": "ניקוי",
    "camera_zone_save": "שמירה",
    "camera_zone_saving": "שומרים…",
    "camera_zone_cancel": "ביטול",
    "camera_zone_save_failed": "לא הצלחנו לשמור את האזור. נסו שוב.",
    "camera_zone_saved": "האזור נשמר",

    "alert_types_title": "להתריע לי על",
    "alert_house_title": "התראות לכל הבית",
    "alert_house_caption": "לכל המצלמות, חוץ ממצלמה שיש לה בחירה משלה.",
    "alert_type_person": "אנשים",
    "alert_type_vehicle": "רכבים",
    "alert_type_animal": "בעלי חיים",
    "alert_hint_person": "כל מי שנמצא בשטח שלכם.",
    "alert_hint_vehicle": "מכוניות שמגיעות או יוצאות. מכונית חונה לא מתריעה.",
    "alert_hint_animal": "חתולים, כלבים ובעלי חיים אחרים. לא ציפורים.",
    "alert_keep_one": "השאירו לפחות אחד פועל. כדי לעצור את כל ההתראות, כבו את התראות האבטחה.",
    "alert_camera_default": "התראות: ברירת המחדל של הבית · {types}",
    "alert_camera_custom": "התראות: {types}",
    "alert_camera_title": "{camera} · להתריע לי על",
    "alert_use_default": "כמו בכל הבית",
    "alert_choose_camera": "לבחור למצלמה הזאת",
    "alert_house_value": "ברירת המחדל של הבית · {types}",
    "alert_custom_one": "מצלמה אחת עם בחירה משלה",
    "alert_custom_many": "{count} מצלמות עם בחירה משלהן",
    "alert_done": "סיום",
    "alert_loading": "טוענים את בחירות ההתראות…",
    "alert_read_error": "לא הצלחנו לקרוא את בחירות ההתראות. פתחו כדי לנסות שוב.",
    "catches_more": "תופס יותר", "sensitivity_house": "כמו בכל הבית", "sensitivity_camera": "לבחור למצלמה הזאת",
    "sensitivity_choose_hint": "הזיזו פס כדי לקבוע אותו למצלמה הזאת. שאר הסוגים נשארים כמו בכל הבית.",
    "sensitivity_unavailable": "ערכי הרגישות לא זמינים. עדכנו את התוכנה בקופסה כדי להשתמש בהם.",
    "sensitivity_custom": "רגישות משלה", "alert_types_custom": "סוגי התראות משלה",
    "camera_detection_title": "{camera} · התראות וזיהוי",

    "owner_title": "בעלי הבית והסכמות",
    "owner_hint": "הוסיפו את בעלי הבית, כדי שהתמיכה של Home Guard תדע את מי לעזור.",
    "owner_name_label": "&שם בעלי הבית (חובה)",
    "owner_phone_label": "&טלפון של בעלי הבית (לא חובה)",
    "installer_label": "שם ה&מתקין (לא חובה)",
    "installer_remembered": "נשמר במחשב הזה להתקנה הבאה שלכם.",
    "owner_permissions": "ההרשאות של בעלי הבית",
    "owner_permissions_hint": "שאלו את בעלי הבית על כל הרשאה. השאירו כבוי אם הם לא מסכימים.",
    "consent_live": "התמיכה של Home Guard יכולה לצפות במצלמות בשידור חי כשמבקשים עזרה.",
    "consent_recordings": "התמיכה של Home Guard יכולה לצפות בהקלטות של התראות שנשמרו.",
    "consent_training": "Home Guard יכול להשתמש בקטעים שלכם כדי ללמד ולשפר את העוזר. הכתובת והפנים שלכם אף פעם לא משותפים.",
    "consent_change_help": "אפשר לשנות את זה בכל זמן בשיחה לתמיכה של Home Guard.",
    "owner_name_error": "הקלידו את שם בעלי הבית (1 עד 120 תווים, בשורה אחת).",
    "owner_phone_error": "עד 200 תווים לטלפון, בשורה אחת, או להשאיר ריק.",
    "installer_error": "עד 120 תווים לשם המתקין, בשורה אחת.",
    "installer_not_remembered": "אפשר להמשיך, אבל לא הצלחנו לזכור את שם המתקין במחשב הזה.",
    "step_register": "מוסיפים את הלקוח ל-Home Guard",
    "demo_setup_register": "שומרים את פרטי בעלי הבית וההרשאות.",

    "language_label": "שפה",
    "language_he": "עברית",
    "language_en": "English",
    "camera_unnamed": "מצלמה",
    "tile_turn_on": "להפעיל",
    "camera_name_save_failed": "לא הצלחנו לשמור את השם \"{name}\". לכל מצלמה צריך שם משלה; נסו שם אחר.",
    "rel_unknown": "לא ידוע", "rel_now": "עכשיו", "rel_seconds": "לפני {n} שנ'", "rel_minutes": "לפני {n} דק'",
    "rel_hours": "לפני {n} שע'", "rel_days": "לפני {n} ימים", "tile_connecting": "מתחברים…",
    "tile_reconnecting": "מתחברים מחדש… {seconds} שנ'", "tile_last_frame": "תמונה אחרונה {when}",
    "remote_read_only": "משנים הגדרות בקופסה עצמה",
    "detections_need_running": "זיהויים מופיעים כש-Home Guard פועל.",
}
