"""All visible application copy; keys remain stable for translation."""

TEXT = {
    "step_error": "This step could not finish. Check the box and try again.",
    "date_format": "%d %b, %H:%M",
    "brand": "HOME GUARD",
    "home": "Your home, in view.",
    "demo": "DEMONSTRATION",
    "collecting": "Collecting",
    "stopped": "Stopped",
    "collection": "Saving clips",
    "inference": "Security alerts",
    "upload": "Last upload",
    "waiting": "Clips waiting",
    "disk": "Disk free",
    "never": "No upload yet",
    "cameras": "Cameras",
    "live": "LIVE",
    "offline": "No picture",
    "offline_hint": "Waiting for a fresh picture",
    "pictures_off": "Camera pictures are switched off",
    "pictures_hint": "Your box keeps working in the background.",
    "empty": "No cameras set up yet",
    "empty_hint": "Ask your installer to add the cameras for this home.",
    "loading": "Checking your box...",
    "error": "Box status is unavailable",
    "error_hint": "Check this box's setup. We'll try again automatically.",
    "activity": "Recent activity",
    "activity_empty": "No recent activity yet",
    "details": "Show details",
    "close_hint": "Closing this window keeps your home protected.",
    "saved": "Clip saved from {camera}",
    "sent": "{count} files sent to the online folder",
    "moved": "{count} clips ready for the online folder",
    "restart": "Collector restarted",
    "upload_error": "The online folder needs attention",
    "warning": "Your box needs attention",
    "reconnect": "Camera is reconnecting",
    "setup": "Set up a home",
    "simulation": "Practice setup / No box will be changed",
    "next": "Continue",
    "back": "Back",
    "start": "Start practice setup",
    "finish": "Start again",
    "retry": "Try again",
    "validation": "Check the highlighted information before continuing.",
    "address_title": "Let's connect your box",
    "address_hint": "Use the box address provided during its first setup.",
    "address": "Box address (user@address)",
    "network_title": "Connect to the home network",
    "network_hint": "Choose the same network that the home's cameras use.",
    "ethernet": "Ethernet cable",
    "wifi": "Wi-Fi",
    "ssid": "Network name",
    "wifi_password": "Network password",
    "house_title": "Make this box feel at home",
    "house_hint": "Give the home a short name using lowercase letters, numbers or underscores.",
    "house": "House name",
    "show": "Show camera pictures on the box",
    "alerts": "Turn on security alerts",
    "hours": "Alert hours (0-23)",
    "camera_title": "Find the home's cameras",
    "camera_hint": "Use the camera or recorder login. You can also do this later.",
    "find": "Find cameras during setup",
    "camera_user": "Camera login name",
    "camera_password": "Camera password",
    "failure": "Practice a network failure",
    "progress_title": "Getting everything ready",
    "progress_hint": "Keep the box powered on while these steps finish.",
    "update": "Update software",
    "name_step": "Set house name and screen preferences",
    "network_step": "Save network and rescue hotspot",
    "camera_step": "Find cameras",
    "readiness": "Check readiness",
    "pending": "Waiting",
    "running": "Working...",
    "PASS": "PASS",
    "WARN": "WARN",
    "FAIL": "FAIL",
    "updated": "Software is up to date",
    "named": "Home preferences saved",
    "network_ok": "Home network and rescue hotspot saved",
    "network_fail": "Could not join the home network. Check the network name and password, then try again.",
    "found": "3 cameras found",
    "skipped": "Find cameras later at the customer's home",
    "ready": "Collector and online folder are ready",
    "summary_title": "Ready for the next step",
    "summary_hint": "Practice complete. Nothing was changed on a real box.",
    "failed_title": "Setup needs your attention",
    "manual": "Before you leave",
    "manual_items": "1. Set power recovery in the box's BIOS to Power On.\n2. Disable access-key expiry in the Tailscale admin console.\n3. Remove the installer's saved Wi-Fi before delivery.\n4. Check camera coverage with the homeowner.",
    "rescue": "Rescue hotspot",
    "rescue_hint": "If the home network changes, use a phone hotspot to recover the box.",
    "rescue_demo": "Practice only / hotspot details will be supplied by the real setup service.",
    "steps": "CONNECT   /   NETWORK   /   HOME   /   CAMERAS   /   READY",
    "camera_count": "{count} cameras",
    "demo_address": "installer@box.example",
    "demo_site": "cedar_house",
    "demo_ssid": "Home network",
    "demo_user": "installer",
    "demo_house": "Cedar House",
    "demo_camera": "Camera {number}",
    "demo_names": [
        "Front door",
        "Garden",
        "Driveway",
        "Side gate",
        "Patio",
        "Garage",
        "Back door",
        "Porch",
        "Courtyard",
    ],
    "demo_events": [
        "Clip saved from front door",
        "13 files sent to the online folder",
        "Collector restarted",
    ],
    "demo_time": "Today, 14:32",
    "gb": "{value:.1f} GB",
    "unknown": "Unavailable",
    "page": "Step {number} of 4",
    "status_rows": "Readiness report",
    "check_collector": "Background collection is ready",
    "check_network": "Home network is ready",
    "check_folder": "Online folder access is ready",
    "check_power": "Check power recovery and sleep settings by hand",
    "ready_warn": "Essential checks passed; check power settings by hand",
    "rescue_name": "Hotspot name",
    "rescue_password": "Hotspot password",
    "service_pending": "Supplied after real setup",
    "separator": " / ",
    "bullet": "-  ",
    "hidden_address": "[address hidden]",
    "hidden": "[hidden]",
    "camera_later": "Find the cameras at the customer's home before delivery.",
}


def tr(key, **values):
    return TEXT[key].format(**values)
